import dotenv from "dotenv";

type SiteEnvTypes = {
  PORT: number;
  MONGO_CONNECTION_STRING_PRODUCTION: string;
  MONGO_CONNECTION_STRING_DEVELOPMENT: string;
  JWT_SECRET: string;
  JWT_EXPIRES_IN: string;
  NODE_ENV: string;
};

dotenv.config();

const { PORT, MONGO_CONNECTION_STRING_DEVELOPMENT, MONGO_CONNECTION_STRING_PRODUCTION, JWT_SECRET, JWT_EXPIRES_IN, NODE_ENV } =
  process.env as unknown as SiteEnvTypes;

export { JWT_EXPIRES_IN, JWT_SECRET, MONGO_CONNECTION_STRING_DEVELOPMENT, MONGO_CONNECTION_STRING_PRODUCTION, NODE_ENV, PORT };
